ARG VERSION
FROM rustembedded/cross:aarch64-unknown-linux-gnu-$VERSION

RUN DEBIAN_FRONTEND=noninteractive dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev:arm64

ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
