ARG VERSION
FROM rustembedded/cross:mips64el-unknown-linux-gnuabi64-$VERSION

ENV OPENSSL_DIR=/usr/local/openssl
RUN git clone https://github.com/openssl/openssl
RUN cd openssl && git checkout OpenSSL_1_1_1h && \
	mkdir -p $OPENSSL_DIR && \
	./Configure linux64-mips64 --prefix=$OPENSSL_DIR --openssldir=$OPENSSL_DIR shared && \
	make CC=mips64el-linux-gnuabi64-gcc && \
	make install
