ARG VERSION
FROM rustembedded/cross:x86_64-unknown-linux-gnu-$VERSION

RUN DEBIAN_FRONTEND=noninteractive dpkg --add-architecture amd64 && \
    apt-get update && \
    apt-get install --assume-yes libssl-dev
